"""
Generate figures from the shipped Final_Vector shapefiles.

Outputs go to Documentation/figures/png and Documentation/figures/pdf.
Run with: python 02_generate_figures.py

Figures produced (mapped to main_paper.md and supplementary_material.md):
  Main paper:
    Fig1   — Statistical conditioning of peer cohorts
    Fig2a  — Field-scale gap distributions by year (violin + box)
    Fig2b  — Field-scale gap distributions by crop (violin + box)
    Fig4   — Targeting curve (% area vs % cumulative reduction potential)
    Fig5   — AMA annual totals grouped bar
  Supplementary:
    FigS6  — County + crop concentration (Pareto bars)
    FigS7  — AMA area-normalized points
    FigS8  — Interannual stability (field count + gap distribution)

Fig 3 (pooled spatial hotspot map) and FigS1–FigS5 (per-year spatial maps)
are generated by 03_generate_supplementary_figures.py.
Fig 6a/6b (sensitivity scatter) are generated by generate_fig6_sensitivity.py.
"""

import os, sys, warnings
import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.ticker as mticker
from matplotlib.lines import Line2D
warnings.filterwarnings('ignore')

import pathlib as _pl
_CLEAN  = _pl.Path(__file__).resolve().parent.parent   # → Documentation/
_IMPL   = _CLEAN.parent                                 # → Implementation/
FV_DIR    = str(_IMPL / 'Final_Vector')
DATA_DIR  = str(_CLEAN / 'data')
OUTDIR    = str(_CLEAN / 'figures' / 'png')
os.makedirs(OUTDIR, exist_ok=True)

# ── shared rcParams (Arial, 11pt base, 300 dpi) ───────────────────────────
plt.rcParams.update({
    'font.family':      'DejaVu Sans',   # fallback if Arial unavailable
    'font.size':        11,
    'axes.titlesize':   12,
    'axes.labelsize':   11,
    'xtick.labelsize':  10,
    'ytick.labelsize':  10,
    'legend.fontsize':  9.5,
    'axes.linewidth':   0.8,
    'grid.linewidth':   0.5,
    'grid.color':       '#dddddd',
    'axes.grid':        True,
    'axes.grid.axis':   'y',
    'axes.axisbelow':   True,
    'figure.dpi':       300,
    'pdf.fonttype':     42,      # TrueType — editable text in Illustrator
    'ps.fonttype':      42,
})
try:
    plt.rcParams['font.family'] = 'Arial'
    import matplotlib.font_manager as fm
    fm.findfont('Arial', fallback_to_default=False)
except Exception:
    plt.rcParams['font.family'] = 'DejaVu Sans'

PDF_DIR = str(_CLEAN / 'figures' / 'pdf')
os.makedirs(PDF_DIR, exist_ok=True)

def savefig_both(fig, stem):
    """Save figure as both PNG (300 dpi) and PDF (vector) for Illustrator."""
    fig.savefig(os.path.join(OUTDIR,  stem + '.png'), dpi=300, bbox_inches='tight')
    fig.savefig(os.path.join(PDF_DIR, stem + '.pdf'), bbox_inches='tight')

CDL_MAP = {1:'Corn', 2:'Cotton', 21:'Barley', 22:'Wheat', 23:'Wheat', 24:'Wheat',
           36:'Alfalfa', 226:'Corn', 228:'Corn', 230:'Wheat', 232:'Cotton',
           233:'Barley', 236:'Wheat'}

# Colorblind-safe palette (Wong 2011) — tested in grayscale
CROP_COLORS = {
    'Alfalfa': '#0072B2',   # blue
    'Wheat':   '#E69F00',   # amber
    'Corn':    '#009E73',   # green
    'Cotton':  '#CC79A7',   # pink/mauve  ← replaces illegible pale yellow
    'Barley':  '#D55E00',   # vermillion
}

print("Loading shapefiles...")
frames = []
for yr in range(2020, 2025):
    f = os.path.join(FV_DIR, f'AZ_AT_ETFullTable_{yr}_5.shp')
    gdf = gpd.read_file(f)[
        ['CSBID','CNTY','CSBACRES','ETmm','ATmm','CDL','Category','VolD','BT']]
    gdf['Year']      = yr
    gdf['Crop']      = gdf['CDL'].map(CDL_MAP)
    gdf['Gap_mm']    = (gdf['ETmm'] - gdf['ATmm']).clip(lower=0)
    gdf['Area_ha']   = gdf['CSBACRES'] * 0.404686
    gdf['VolD_clip'] = gdf['VolD'].clip(lower=0)
    gdf['VolD_AF']   = gdf['VolD_clip'] / 1233.48
    frames.append(gdf)

df = pd.concat(frames, ignore_index=True)
print(f"  {len(df):,} field-years loaded")

# ─────────────────────────────────────────────────────────────────────────
# Helper: violin + box plot
# ─────────────────────────────────────────────────────────────────────────
def draw_violin_box(ax, data_list, labels, colors, ylim_top=950):
    vp = ax.violinplot(data_list, positions=range(len(data_list)),
                       showmedians=False, showextrema=False, widths=0.72)
    for body, col in zip(vp['bodies'], colors):
        body.set_facecolor(col); body.set_alpha(0.60); body.set_edgecolor('none')

    for i, data in enumerate(data_list):
        q1, med, q3 = np.percentile(data, [25, 50, 75])
        p10, p90    = np.percentile(data, [10, 90])
        # whiskers P10–P90
        ax.vlines(i, p10, p90, color='black', linewidth=1.2, zorder=3)
        ax.hlines(p10, i-0.08, i+0.08, color='black', linewidth=1.2, zorder=3)
        ax.hlines(p90, i-0.08, i+0.08, color='black', linewidth=1.2, zorder=3)
        # IQR box
        rect = mpatches.Rectangle((i-0.15, q1), 0.30, q3-q1,
                                   facecolor='white', edgecolor='black',
                                   linewidth=1.2, zorder=4)
        ax.add_patch(rect)
        ax.hlines(med, i-0.15, i+0.15, color='black', linewidth=2.0, zorder=5)

    ax.set_xticks(range(len(labels)))
    ax.set_xticklabels(labels, fontsize=10)
    ax.set_ylim(0, ylim_top)
    ax.set_xlim(-0.6, len(labels)-0.4)
    ax.text(0.98, 0.97,
            'Box: IQR  |  Line: median\nWhiskers: 10th–90th percentile',
            transform=ax.transAxes, fontsize=8, va='top', ha='right',
            bbox=dict(boxstyle='round,pad=0.3', fc='white', ec='#cccccc', alpha=0.9))

# ══════════════════════════════════════════════════════════════════════════
# FIG 2a — Gap by year
# ══════════════════════════════════════════════════════════════════════════
print("Fig 2a...")
YEAR_COLORS = ['#4daf4a','#e07050','#6baed6','#cc79a7','#74c476']
years = list(range(2020, 2025))
data  = [df[df.Year==yr]['Gap_mm'].values for yr in years]
ns    = [df[df.Year==yr].shape[0] for yr in years]
labels = [f'{yr}\n(n={n:,})' for yr, n in zip(years, ns)]

fig, ax = plt.subplots(figsize=(8.5, 5))
draw_violin_box(ax, data, labels, YEAR_COLORS)
ax.set_xlabel('Year', fontsize=11)
ax.set_ylabel('Attainable-ET gap (mm)', fontsize=11)
plt.tight_layout()
savefig_both(fig, 'Fig2a_gap_by_year')
plt.close()
print("  saved")

# ══════════════════════════════════════════════════════════════════════════
# FIG 2b — Gap by crop, ordered by median descending
# ══════════════════════════════════════════════════════════════════════════
print("Fig 2b...")
crop_order = (df.groupby('Crop')['Gap_mm'].median()
                .sort_values(ascending=False).index.tolist())
data_c  = [df[df.Crop==c]['Gap_mm'].values for c in crop_order]
ns_c    = [df[df.Crop==c].shape[0] for c in crop_order]
cols_c  = [CROP_COLORS[c] for c in crop_order]
labels_c = [f'{c}\n(n={n:,})' for c, n in zip(crop_order, ns_c)]

fig, ax = plt.subplots(figsize=(8.5, 5))
draw_violin_box(ax, data_c, labels_c, cols_c)
ax.set_xlabel('Crop', fontsize=11)
ax.set_ylabel('Attainable-ET gap (mm)', fontsize=11)
# add "pooled 2020-2024" note
ax.text(0.02, 0.97, 'Pooled 2020–2024', transform=ax.transAxes,
        fontsize=9, va='top', color='#555555')
plt.tight_layout()
savefig_both(fig, 'Fig2b_gap_by_crop')
plt.close()
print("  saved")

# ══════════════════════════════════════════════════════════════════════════
# FIG 4 — Targeting curve
# ══════════════════════════════════════════════════════════════════════════
print("Fig 4 (targeting curve)...")
YR_PAL = ['#bdd7e7','#6baed6','#2171b5','#084594','#08306b']

fig, ax = plt.subplots(figsize=(7, 5.5))
for i, yr in enumerate(years):
    d = df[df.Year==yr].copy()
    d = d[d['VolD_AF']>0].sort_values('VolD_AF', ascending=False)
    d['cum_vol']  = d['VolD_AF'].cumsum()
    d['cum_area'] = d['Area_ha'].cumsum()
    tv, ta = d['VolD_AF'].sum(), d['Area_ha'].sum()
    ax.plot(d['cum_area']/ta*100, d['cum_vol']/tv*100,
            color=YR_PAL[i], linewidth=1.3, alpha=0.85, label=str(yr))

# Pooled (farm-average across years)
pooled = df.groupby('CSBID').agg(Area_ha=('Area_ha','mean'),
                                  VolD_AF=('VolD_AF','mean')).reset_index()
pooled = pooled[pooled['VolD_AF']>0].sort_values('VolD_AF', ascending=False)
pooled['cum_vol']  = pooled['VolD_AF'].cumsum()
pooled['cum_area'] = pooled['Area_ha'].cumsum()
tv_p, ta_p = pooled['VolD_AF'].sum(), pooled['Area_ha'].sum()
p_pct_area = pooled['cum_area']/ta_p*100
p_pct_vol  = pooled['cum_vol'] /tv_p*100
ax.plot(p_pct_area, p_pct_vol, color='#08306b', linewidth=2.8,
        label='Pooled 2020–2024', zorder=5)

# Reference lines and annotation
thresh = float(p_pct_area[p_pct_vol >= 50].iloc[0])
ax.axhline(50,       color='#777777', linewidth=0.85, linestyle='--', zorder=2)
ax.axvline(thresh,   color='#777777', linewidth=0.85, linestyle='--', zorder=2)
ax.annotate(f'{thresh:.1f}% of area\n→ 50% of volume',
            xy=(thresh, 50), xytext=(thresh+8, 36),
            fontsize=9, color='#333333',
            arrowprops=dict(arrowstyle='->', color='#777777', lw=0.9))

ax.set_xlabel('Targeted fields (% of irrigated area, ranked by reduction potential)',
              fontsize=11)
ax.set_ylabel('Cumulative reduction potential\n(% of annual total)', fontsize=11)
ax.set_xlim(0, 100); ax.set_ylim(0, 100)
ax.xaxis.set_major_formatter(mticker.FormatStrFormatter('%g%%'))
ax.yaxis.set_major_formatter(mticker.FormatStrFormatter('%g%%'))

handles = [Line2D([0],[0], color=YR_PAL[i], lw=1.3, label=str(yr))
           for i, yr in enumerate(years)]
handles.append(Line2D([0],[0], color='#08306b', lw=2.8, label='Pooled 2020–2024'))
ax.legend(handles=handles, loc='lower right', framealpha=0.9)

plt.tight_layout()
savefig_both(fig, 'Fig4_targeting_curve')
plt.close()
print("  saved")

# ══════════════════════════════════════════════════════════════════════════
# FIG 5 — County & crop concentration (Pareto)
# ══════════════════════════════════════════════════════════════════════════
print("Fig S6 (county/crop concentration)...")
tot = df['VolD_AF'].sum()
by_cnty = df.groupby('CNTY')['VolD_AF'].sum().sort_values(ascending=False)
by_crop = df.groupby('Crop')['VolD_AF'].sum().sort_values(ascending=False)

# County: show top 6 + "Other"
TOP_N_CNTY = 6
cnty_top = by_cnty.head(TOP_N_CNTY)
cnty_other = pd.Series({'Other': by_cnty.iloc[TOP_N_CNTY:].sum()})
by_cnty_plot = pd.concat([cnty_top, cnty_other])

fig, axes = plt.subplots(1, 2, figsize=(13, 5.5))
for ax, by_cat, xlabel in zip(
        axes,
        [by_cnty_plot, by_crop],
        ['County', 'Crop']):

    pcts = by_cat / tot * 100
    cum  = pcts.cumsum().values
    cats = pcts.index.tolist()
    x    = np.arange(len(cats))

    # Use lighter color for "Other" bar
    colors = ['#4C9BE8'] * len(cats)
    if 'Other' in cats:
        colors[cats.index('Other')] = '#B0B0B0'

    bars = ax.bar(x, pcts.values, color=colors, edgecolor='white',
                  linewidth=0.5, width=0.65)

    ax2 = ax.twinx()
    ax2.plot(x, cum, 'o-', color='#1a1a2e', linewidth=1.6, markersize=5, zorder=5)
    ax2.set_ylim(0, 108)
    ax2.set_ylabel('Cumulative share (%)', fontsize=10)
    ax2.yaxis.set_major_formatter(mticker.FormatStrFormatter('%g%%'))
    ax2.tick_params(axis='y', labelsize=9)
    ax2.grid(False)

    ax.set_xticks(x)
    ax.set_xticklabels(cats, rotation=0, ha='center', fontsize=9.0)
    ax.set_ylabel('Share of total reduction potential (%)', fontsize=10)
    ax.set_xlabel(xlabel, fontsize=11, labelpad=4)
    ax.yaxis.set_major_formatter(mticker.FormatStrFormatter('%g%%'))
    ax.set_ylim(0, pcts.max() * 1.32)
    ax.grid(False)
    for bar, pct in zip(bars, pcts.values):
        if pct >= 2.5:
            ax.text(bar.get_x() + bar.get_width()/2,
                    bar.get_height() + 0.3,
                    f'{pct:.1f}%', ha='center', va='bottom', fontsize=7.5)

fig.tight_layout(pad=1.5)
savefig_both(fig, 'FigS6_county_crop_concentration')
plt.close()
print("  saved")

# ══════════════════════════════════════════════════════════════════════════
# FIG 6 — Interannual stability
# ══════════════════════════════════════════════════════════════════════════
print("Fig S8 (interannual stability)...")
n_fields = [df[df.Year==yr].shape[0] for yr in years]
area_kha  = [df[df.Year==yr]['Area_ha'].sum()/1e3 for yr in years]
med_gap   = [df[df.Year==yr]['Gap_mm'].median() for yr in years]
q1_gap    = [df[df.Year==yr]['Gap_mm'].quantile(0.25) for yr in years]
q3_gap    = [df[df.Year==yr]['Gap_mm'].quantile(0.75) for yr in years]
p90_gap   = [df[df.Year==yr]['Gap_mm'].quantile(0.90) for yr in years]

C_BAR, C_LINE = '#4C9BE8', '#E07050'
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# (a) fields and area — BOTH y-axes from zero
ax1.bar(years, n_fields, color=C_BAR, alpha=0.80, width=0.6, label='Fields')
ax1.set_ylabel('Benchmarked fields (count)', fontsize=10, color=C_BAR)
ax1.tick_params(axis='y', labelcolor=C_BAR, labelsize=9)
ax1.set_ylim(0, max(n_fields)*1.28)
ax1.set_xticks(years); ax1.set_xlabel('Year', fontsize=11)

ax1b = ax1.twinx()
ax1b.plot(years, area_kha, 'o-', color=C_LINE, linewidth=2, markersize=6, zorder=5)
ax1b.set_ylabel('Benchmarked area (×10³ ha)', fontsize=10, color=C_LINE)
ax1b.tick_params(axis='y', labelcolor=C_LINE, labelsize=9)
ax1b.set_ylim(0, max(area_kha)*1.28)   # from zero — not misleading

h1 = mpatches.Patch(color=C_BAR, alpha=0.80, label='Fields (count)')
h2 = Line2D([0],[0], color=C_LINE, lw=2, marker='o', label='Area (×10³ ha)')
ax1.legend(handles=[h1,h2], loc='upper right', fontsize=9)
ax1.grid(axis='y'); ax1.set_axisbelow(True)

# (b) gap statistics
ax2.fill_between(years, q1_gap, q3_gap, alpha=0.22, color=C_BAR, label='IQR')
ax2.fill_between(years, q3_gap, p90_gap, alpha=0.10, color=C_BAR, label='IQR–P90')
ax2.plot(years, med_gap, 'o-', color='#08306b', lw=2, ms=6, label='Median', zorder=5)
ax2.plot(years, p90_gap, 's--', color=C_LINE, lw=1.5, ms=5, label='P90', zorder=4)

for yr, med in zip(years, med_gap):
    ax2.annotate(f'{med:.0f}', xy=(yr, med), xytext=(0, 9),
                 textcoords='offset points', ha='center', fontsize=8.5, color='#08306b')

ax2.set_xlabel('Year', fontsize=11)
ax2.set_ylabel('Attainable-ET gap (mm)', fontsize=11)
ax2.set_ylim(0, max(p90_gap)*1.22)
ax2.set_xticks(years)
ax2.legend(loc='upper right', fontsize=9)
ax2.grid(axis='y')

plt.tight_layout()
savefig_both(fig, 'FigS8_interannual_stability')
plt.close()
print("  saved")

# ══════════════════════════════════════════════════════════════════════════
# FIG 7 — AMA annual totals (grouped bar, consistent AMA order)
# ══════════════════════════════════════════════════════════════════════════
print("Fig 5 (AMA yearly bars)...")
ama_wide = pd.read_csv(os.path.join(DATA_DIR, 'ama',
    'ama_savings_by_ama_year_wide_af_2020_2024.csv'))
outside  = pd.read_csv(os.path.join(DATA_DIR, 'ama',
    'outside_ama_savings_by_year_2020_2024.csv'))

# Clean AMA names (remove " AMA" suffix for labels)
ama_wide['Label'] = ama_wide['BASIN_NAME'].str.replace(' AMA','', regex=False)
ama_wide = ama_wide[ama_wide['Label'] != 'PRESCOTT']   # zero fields, drop

# Order by pooled total descending
ama_wide['total'] = ama_wide[[str(y) for y in years]].sum(axis=1)
ama_wide = ama_wide.sort_values('total', ascending=False)

labels_ama = list(ama_wide['Label'].str.title())
x = np.arange(len(labels_ama))
width = 0.15
yr_colors = ['#08306b','#2171b5','#4292c6','#6baed6','#bdd7e7']

fig, ax = plt.subplots(figsize=(11, 5.5))
for i, (yr, col) in enumerate(zip(years, yr_colors)):
    vals = ama_wide[str(yr)].fillna(0).values / 1e3   # thousands AF
    offset = (i - 2) * width
    ax.bar(x + offset, vals, width, color=col, label=str(yr),
           edgecolor='white', linewidth=0.4)

# Outside AMA as light-gray hatched bar at the end
out_vals = outside.set_index('Year')['total_savings_af'] / 1e3
x_out = len(labels_ama)
for i, (yr, col) in enumerate(zip(years, yr_colors)):
    offset = (i - 2) * width
    ax.bar(x_out + offset, out_vals.get(yr, 0), width, color=col,
           alpha=0.45, edgecolor='#888888', linewidth=0.4, hatch='//')

labels_ama.append('Outside AMA')
ax.set_xticks(np.append(x, x_out))
ax.set_xticklabels(labels_ama, rotation=0, fontsize=10)
ax.set_ylabel('Total reduction potential (10³ acre-feet)', fontsize=11)
ax.set_xlabel('Active Management Area', fontsize=11)
ax.yaxis.set_major_formatter(mticker.FormatStrFormatter('%g'))
ax.legend(title='Year', fontsize=9, title_fontsize=9.5, loc='upper right')
ax.set_ylim(0, None)
# note for outside AMA
ax.text(x_out, -ax.get_ylim()[1]*0.08, 'Hatched:\noutside AMA',
        ha='center', fontsize=7.5, color='#666666')

plt.tight_layout()
savefig_both(fig, 'Fig5_AMA_yearly_bars')
plt.close()
print("  saved")

# ══════════════════════════════════════════════════════════════════════════
# FIG 8 — AMA area-normalized (per-AMA colors, IQR+median, jitter)
# Matches original plot_fig_ama_area_normalized_points.py style
# ══════════════════════════════════════════════════════════════════════════
print("Fig S7 (AMA area-normalized)...")
ama_long = pd.read_csv(os.path.join(DATA_DIR, 'ama/ama_savings_2020_2024.csv'))
ama_long['Label'] = ama_long['BASIN_NAME'].str.replace(' AMA', '', regex=False).str.title()
ama_long = ama_long[ama_long['Label'].str.upper() != 'PRESCOTT'].copy()

out8 = outside.copy()
out8['Label'] = 'Outside AMA'

AMA_COLORS = {
    'Phoenix':     '#4E79A7',
    'Santa Cruz':  '#F28E2B',
    'Pinal':       '#59A14F',
    'Douglas':     '#E15759',
    'Willcox':     '#76B7B2',
    'Tucson':      '#B07AA1',
    'Outside AMA': '#BDBDBD',
}

# Order AMAs by median savings_mm descending
order8 = (ama_long.groupby('Label')['savings_mm'].median()
          .sort_values(ascending=False).index.tolist())
order8.append('Outside AMA')

fig, ax = plt.subplots(figsize=(8.5, 5.5))

rng8 = np.random.default_rng(42)
all_vals8 = []
for i, lbl in enumerate(order8):
    if lbl == 'Outside AMA':
        sub8 = out8[['savings_mm']].copy()
        marker8, edge8 = 'D', '#333333'
    else:
        sub8 = ama_long[ama_long['Label'] == lbl][['savings_mm']].copy()
        marker8, edge8 = 'o', 'none'
    col8 = AMA_COLORS.get(lbl, '#4E79A7')
    jitter8 = rng8.uniform(-0.08, 0.08, size=len(sub8))
    ax.scatter(i + jitter8, sub8['savings_mm'], color=col8, s=35,
               marker=marker8, edgecolor=edge8, linewidth=0.8, alpha=0.9, zorder=3)
    q1_8 = sub8['savings_mm'].quantile(0.25)
    q3_8 = sub8['savings_mm'].quantile(0.75)
    med8 = sub8['savings_mm'].median()
    ax.plot([i, i], [q1_8, q3_8], color='#444444', linewidth=3, zorder=2)
    ax.plot([i-0.12, i+0.12], [med8, med8], color='#111111', linewidth=2, zorder=4)
    all_vals8.extend(sub8['savings_mm'].tolist())

# Separator before Outside AMA
ax.axvline(len(order8) - 1.5, color='#999999', linewidth=0.8, alpha=0.6)
# Statewide median reference
statewide_med8 = ama_long['savings_mm'].median()
ax.axhline(statewide_med8, color='#999999', linestyle='--', linewidth=0.8,
           alpha=0.6, zorder=1, label=f'Statewide median ({statewide_med8:.0f} mm)')

ax.set_xticks(range(len(order8)))
ax.set_xticklabels(order8, rotation=0, ha='center', fontsize=10)
ax.set_ylabel(r'Area-normalized reduction potential (mm $\mathrm{yr}^{-1}$)', fontsize=11)
ax.set_xlabel('Active Management Area', fontsize=11)
ypad8 = (max(all_vals8) - min(all_vals8)) * 0.1
ax.set_ylim(max(0, min(all_vals8) - ypad8), max(all_vals8) + ypad8)
ax.legend(fontsize=8.5, loc='upper right')
ax.grid(axis='y')
ax.set_axisbelow(True)

plt.tight_layout()
savefig_both(fig, 'FigS7_AMA_area_normalized')
plt.close()
print("  saved")


# Fig 6a and Fig 6b (sensitivity scatter) are generated by
# generate_fig6_sensitivity.py.


# ══════════════════════════════════════════════════════════════════════════
# FIG 1 — Statistical conditioning of peer cohorts
#   (a) Distribution of benchmarked fields by cohort sample size
#   (b) Width of 95% CI for 5th-pct ET as a function of cohort size
# ══════════════════════════════════════════════════════════════════════════
print("Fig 1 (statistical conditioning of peer cohorts)...")

BIN_ORDER = ['<5', '5-9', '10-19', '20-29', '30-49', '50-99', '100-199', '200+']

bin_overall = pd.read_csv(os.path.join(DATA_DIR, 'cohort/cohort_size_bins_overall.csv'))
ci_df = pd.read_csv(os.path.join(DATA_DIR, 'cohort/cohort_p5_ci_summary_by_bin.csv'))

bin_overall['size_bin'] = pd.Categorical(bin_overall['size_bin'], BIN_ORDER, ordered=True)
bin_overall = bin_overall.sort_values('size_bin')

ci_df['size_bin'] = pd.Categorical(ci_df['size_bin'], BIN_ORDER, ordered=True)
ci_stats = (
    ci_df.groupby('size_bin', as_index=False)
         .agg(median_ci_width=('median_ci_width', 'median'),
              q25=('median_ci_width', lambda x: x.quantile(0.25)),
              q75=('median_ci_width', lambda x: x.quantile(0.75)))
         .sort_values('size_bin')
)

fig1, axes1 = plt.subplots(1, 2, figsize=(11, 4.2))

# Panel (a): cohort size distribution
ax1a = axes1[0]
ax1a.bar(bin_overall['size_bin'], bin_overall['pct_fields'],
         color='#4D4D4D', edgecolor='none', width=0.55)
ax1a.set_ylabel('Fields (%)', fontsize=11)
ax1a.set_xlabel('Cohort size (N)', fontsize=11, labelpad=2)
ax1a.set_ylim(0, min(100, bin_overall['pct_fields'].max() * 1.20))
ax1a.grid(axis='y', color='#bbbbbb', alpha=0.3, linewidth=0.5)
ax1a.set_axisbelow(True)
ax1a.set_facecolor('white')
for side in ('top', 'right'):
    ax1a.spines[side].set_visible(False)
ax1a.tick_params(axis='both', length=2.5, labelsize=9)

# Panel (b): CI width vs cohort size
ax1b = axes1[1]
lc = '#1F77B4'
ax1b.plot(ci_stats['size_bin'], ci_stats['median_ci_width'],
          color=lc, linewidth=2.4, marker='o', markersize=4)
ax1b.fill_between(ci_stats['size_bin'], ci_stats['q25'], ci_stats['q75'],
                  color=lc, alpha=0.15)
ax1b.set_ylabel('Width of 95% CI for P5 ET (mm)', fontsize=11)
ax1b.set_xlabel('Cohort size (N)', fontsize=11, labelpad=2)
ax1b.grid(axis='y', color='#bbbbbb', alpha=0.3, linewidth=0.5)
ax1b.set_axisbelow(True)
ax1b.set_facecolor('white')
for side in ('top', 'right'):
    ax1b.spines[side].set_visible(False)
ax1b.tick_params(axis='both', length=2.5, labelsize=9)

plt.tight_layout()
savefig_both(fig1, 'Fig1_cohort_conditioning')
plt.close()
print("  saved")


print()
print("All figures saved to:")
print(f"  PNG: {OUTDIR}")
print(f"  PDF: {PDF_DIR}")
print("Files:")
for f in sorted(os.listdir(OUTDIR)):
    sz = os.path.getsize(os.path.join(OUTDIR, f)) // 1024
    print(f"  {f}  ({sz} KB)")
